name = "clintrials-mcp"
main = "src/index.ts"
compatibility_date = "2024-10-05"

[vars]
# Set your FastMCP backend URL here
# For local development, use a tunnel service like ngrok or cloudflared
# BACKEND_URL = "https://your-backend-url.com"

[dev]
# Align local dev port with docs/examples
port = 8788
